apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ value.metadata.name }}
  labels:
    app: {{ value.metadata.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ value.metadata.labels.app }}
      tier:{{ value.spec.selector.matchLabels.tier }}
  strategy:
    type: {{ value.spec.strategy.type. }}
  template:
    metadata:
      labels:
        app:  {{ value.template.metadata.labels.app }}
        tier:   {{ value.template.tier }}
    spec:
      containers:
      - image:   {{ value.spec.containers.image }}
        name:  {{ value.spec.containers.name }}
        env:
        - name:  {{ value.spec.env.name }}
          valueFrom:
            secretKeyRef:
              name:  {{ value.spec.containers.valueFrom.name }}
              key:  {{ value.spec.containers.valueFrom.key }}
        ports:
        - containerPort:  {{ value.spec.containers.ports.containerPort }}
          name: {{ value.spec.containers.ports.name }}
        volumeMounts:
        - name: {{ value.spec.volumeMounts.name }}
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ value.spec.volumes.name }}
        persistentVolumeClaim:
          claimName: {{ value.spec.volumes.persistentVolumeClaim.claimName }}
